# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.iedr.ie/ie/status_registered_new_format.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.iedr.ie", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.iedr.ie/ie/status_registered_new_format.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.iedr.ie")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered_new_format.expected" do
    expect(subject.disclaimer).to eq("Important Notice If you believe that information published on this page is incorrect, or should not be published,please contact your Registrar, or the .IE Registration Services Department who will advise you further. You can also contact your Registrar or .IE if your Registrant name is not showing and you would like it to be published. Our contact information is available at https://www.weare.ie/contact-us/ Rights restricted by copyright: https://www.weare.ie/registrant-terms-conditions-policy/ Do not remove this notice")
    expect(subject.domain).to eq("google.ie")
    expect(subject.domain_id).to eq("762999-IEDR")
    expect(subject.status).to eq(:registered)
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(Time.parse("2002-03-21T00:00:00Z"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(Time.parse("2025-05-05T14:18:36Z"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(Time.parse("2026-03-21T14:13:27Z"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.name).to eq("Markmonitor Inc")
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].name).to eq("Google LLC")
    expect(subject.registrant_contacts[0].id).to eq("379250-IEDR")
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts.size).to eq(0)
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts.size).to eq(0)
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(3)
    expect(subject.nameservers[0]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[0].name).to eq("ns1.google.com")
    expect(subject.nameservers[1]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[1].name).to eq("ns2.google.com")
    expect(subject.nameservers[2]).to be_a(Whois::Parser::Nameserver)
    expect(subject.nameservers[2].name).to eq("ns3.google.com")
  end
end
